### ISSUE TITLE
Exception using `Client.notify()`

### ISSUE THREAD

**Issue by TimBarham** [tiny-jsonrpc/tiny-jsonrpc-postmessage#13]
First off... thanks for a great little JSON-RPC client/server that works with web workers. Just what I was looking for :smile:.

However, I'm getting an exception like the following whenever I use `Client.notify()`:

`Uncaught TypeError: Cannot read property 'result' of null`

The error occurs on [this line](https://github.com/tiny-jsonrpc/tiny-jsonrpc-postmessage/blob/master/lib/tiny-jsonrpc-postmessage/client.js#L77).

I've tracked down the cause:
* When using notify, `request.id` is undefined (as expected).
* `Server._respond()` calls `makeResponse()` ([here](https://github.com/tiny-jsonrpc/tiny-jsonrpc/blob/master/lib/tiny-jsonrpc/server.js#L328)). Since `request.id` is undefined, `makeResponse()` returns `null`.
* `_respondCallback()` in `Server.respond()` stringifies `response` ([here](https://github.com/tiny-jsonrpc/tiny-jsonrpc/blob/master/lib/tiny-jsonrpc/server.js#L209)), resulting in the string, "null", and passes that to the callback.
* `this.respond()` callback in `PostMessageServer._onMessage()` passes that response to `_client.postMessage()` ([here](https://github.com/tiny-jsonrpc/tiny-jsonrpc-postmessage/blob/master/lib/tiny-jsonrpc-postmessage/server.js#L50))
* `PostMessageClient._onMessage()` assumes e.data is a valid JSONRPC response and tries to get properties of `null`.

I can provide a repro if you need it, but I'm pretty sure this will happen with any `notify` call. I'm working around it by adding a null check in `PostMessageClient._onMessage()` (and also `PostMessageServer._onMessage()` as the same problem can occur there), but I suspect that really you don't even want to post the message in this scenario.

**Comment by lawnsea** [comment]
Wow, thanks for the awesome bug report!

No repro necessary. I'll write a failing test and get this fixed. Thanks!

**Comment by lawnsea** [comment]
A fix for this is released as v3.0.2
