### ISSUE TITLE
Client.request() callback not called if provider returns falsy value

### ISSUE THREAD

**Issue by TimBarham** [tiny-jsonrpc/tiny-jsonrpc-postmessage#15]
If the provider for a `request()` call returns a falsy value, the request callback is never called.

This is because in `PostMessageClient.prototype._onMessage()` ([here](https://github.com/tiny-jsonrpc/tiny-jsonrpc-postmessage/blob/master/lib/tiny-jsonrpc-postmessage/client.js#L77)), `data.result` is falsy, so it immediately returns.

**Comment by TimBarham** [comment]
Also, once that is fixed, [this](https://github.com/tiny-jsonrpc/tiny-jsonrpc-postmessage/blob/master/lib/tiny-jsonrpc-postmessage/client.js#L91) line in the same method will convert all falsy return values to `null`.

**Comment by lawnsea** [comment]
Bummer. I'll get a fix going for this tomorrow. Thanks again for the great bug report!

**Comment by lawnsea** [comment]
Published a fix for this as v3.0.3
